### ISSUE TITLE
appointmentRender Rendering multiple times (React)

### ISSUE THREAD

**Issue by facuesr** [DevExpress/devextreme-react#411] opened 2020-03-26 21:17 UTC
### Steps to Reproduce:

1. JS dev extreme demo page. https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/CustomTemplates/React/Light/
2. Check that the component in AppointmentTemplate.js is rendering a lot of times in week view. Also when it shows the tooltip, it renders again all the appointments. 
3. Should render 1 time for each appointment. This error makes the scheduler very slow when using a weekly or monthly view with many appointments.

**Comment by IlyaKhD** [comment] 2020-04-17 09:33
Hello!

Thank you for your report. I reproduced this issue and we'll investigate it. We will update this thread once we have any news.

**Comment by facuesr** [comment] 2020-10-29 21:12
hi @IlyaKhD do you have any news about this? Thanks

**Comment by IlyaKhD** [comment] 2020-10-30 10:39
Hi @facuesr, we're testing a complex fix for this at the moment. By the way, what DevExtreme version do you use?

**Comment by facuesr** [comment] 2020-10-30 11:49
Hi @IlyaKhD I'm using dev extreme & dev extreme react version 20.1.7.

**Comment by IlyaKhD** [comment] 2020-10-30 13:31
I'm closing this thread since there is a related [issue in our Support Center](https://supportcenter.devexpress.com/ticket/details/t933359/scheduler-rendering-is-slow-when-datacellcomponent-is-specified-and-when-switching-views). It contains a workaround, and can be added to favorites to keep track of updates.
Thanks!

**Closed by IlyaKhD** 2020-10-30 13:31 UTC
Labels: bug
