### ISSUE TITLE
Bug report: DataGrid editCellComponent not working

### ISSUE THREAD

**Issue by amarkstar** [DevExpress/devextreme-react#180] opened 2018-08-30 03:20 UTC
### Issue Type
Bug report

### Description
The issue is related to DataGrid editCellComponent, error thrown when loses focus edit component.

#### Steps to Reproduce
1. Click Row cell
2. Click other then row cell (onblur)

#### Current Behavior
Error thrown: Error in /turbo_modules/react-dom@16.1.1/cjs/react-dom.development.js (15067:22)
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

#### Expected Behavior
Fit and don't throw error

#### Demo
https://stackblitz.com/edit/react-mzbcg4

### Environment Details
- devextreme version:18.1.5
- devextreme-react version:18.1.5
- react version:16.1

**Comment by lukyanovas** [comment] 2018-09-02 09:49
duplicate of https://github.com/DevExpress/devextreme-react/issues/162

**Closed by lukyanovas** 2018-09-02 09:49 UTC
Labels: bug, duplicate
